import nullVectorImg from '../assets/event_null_vector.png'
import kineticEngineImg from '../assets/event_kinetic_engine.png'
import sigmaBreachImg from '../assets/event_sigma_breach.png'
import offgridImg from '../assets/event_offgrid.png'

export const FILTERS = ['ALL OPS', 'BOOTCAMP', 'WORKSHOP', 'SESSION', 'HACKATHON']

export const EVENTS = [
  {
    id: 1,
    eventStatus: 'upcoming',
    title: 'DEV 103',
    tags: ['BOOTCAMP'],
    tagColors: ['blue'],
    image: kineticEngineImg,
    description: 'Full-Stack Development Bootcamp. An advanced bootcamp covering modern web technologies, cloud deployment, and best practices for production-grade applications.',
    entryFee: 'Free',
    date: 'TBD',
    venue: 'CPBYTE Campus',
    slotsLeft: 'TBD',
    duration: '5 days',
    difficulty: 'Intermediate',
    leadOp: 'CPBYTE Team',
    daysLeft: 30,
  },
  {
    id: 2,
    eventStatus: 'upcoming',
    title: 'OPEN SOURCE SPRINT',
    tags: ['WORKSHOP'],
    tagColors: ['purple'],
    image: sigmaBreachImg,
    description: 'Collaborate on real open-source projects. Learn how to contribute to the open-source ecosystem, create pull requests, and build your GitHub profile.',
    entryFee: 'Free',
    date: 'TBD',
    venue: 'Online · Discord',
    slotsLeft: 'TBD',
    duration: '2 days',
    difficulty: 'All Levels',
    daysLeft: 60,
  },
  {
    id: 3,
    eventStatus: 'completed',
    title: 'OFF-GRID 2.0',
    tags: ['HACKATHON'],
    tagColors: ['red'],
    image: offgridImg,
    description: 'A 36-hour high-energy offline hackathon at KIET Ghaziabad. Fixed tech stack + random problem statement — no comfort zone allowed. Racing-themed categories: Sector 1 & 2 Circuit Challenge. Online shortlisting followed by offline execution.',
    entryFee: 'Free',
    date: '10 Apr, 2026',
    venue: 'KIET Ghaziabad',
    slotsLeft: '40+ Teams',
    duration: '36 hours',
    difficulty: 'Advanced',
    result: '50,000+ Prize Pool · 40+ Teams',
  },
  {
    id: 4,
    eventStatus: 'completed',
    title: 'DEV 102',
    tags: ['BOOTCAMP'],
    tagColors: ['blue'],
    image: kineticEngineImg,
    description: 'Backend Bootcamp covering Springboot, NODEjs, Docker, Git & Github. A comprehensive bootcamp on backend development essentials for beginners.',
    entryFee: 'Free',
    date: '07 Apr, 2025',
    venue: 'CPBYTE Campus',
    slotsLeft: '400 / 400',
    duration: '5 days',
    difficulty: 'Beginner',
    result: '400 Participants',
  },
  {
    id: 4,
    eventStatus: 'completed',
    title: 'SPEAKER SESSION',
    tags: ['SESSION'],
    tagColors: ['gold'],
    image: nullVectorImg,
    description: 'Technical Speaker Session with Prince Kumar & M.Rehman (SWE-2 Google). A collaborative session by CPBYTE x DEVUP featuring industry experts.',
    entryFee: 'Free',
    date: '21 Feb, 2025',
    venue: 'CPBYTE Campus',
    slotsLeft: '300 / 300',
    duration: '1 day',
    difficulty: 'All Levels',
    result: '300 Participants',
  },
  {
    id: 5,
    eventStatus: 'completed',
    title: 'DEV 101',
    tags: ['BOOTCAMP'],
    tagColors: ['blue'],
    image: kineticEngineImg,
    description: 'Web & Android Dev Bootcamp. A bootcamp on Web, Android Development and Git & GitHub Essentials for beginners.',
    entryFee: 'Free',
    date: '04 Oct, 2024',
    venue: 'CPBYTE Campus',
    slotsLeft: '400 / 400',
    duration: '3 days',
    difficulty: 'Beginner',
    result: '400 Participants',
  },
  {
    id: 6,
    eventStatus: 'completed',
    title: 'REACT 101',
    tags: ['BOOTCAMP'],
    tagColors: ['blue'],
    image: sigmaBreachImg,
    description: 'React Bootcamp. A bootcamp on React for beginners covering components, hooks, state management, and building real-world applications.',
    entryFee: 'Free',
    date: '26 Apr, 2024',
    venue: 'CPBYTE Campus',
    slotsLeft: '250 / 250',
    duration: '3 days',
    difficulty: 'Beginner',
    result: '250 Participants',
  },
  {
    id: 7,
    eventStatus: 'completed',
    title: 'CODE CRAFT',
    tags: ['WORKSHOP'],
    tagColors: ['purple'],
    image: nullVectorImg,
    description: 'UI/UX Design Workshop. A workshop on UI/UX design for beginners covering design principles, Figma, prototyping, and user research.',
    entryFee: 'Free',
    date: '15 May, 2024',
    venue: 'CPBYTE Campus',
    slotsLeft: '250 / 250',
    duration: '3 days',
    difficulty: 'Beginner',
    result: '250 Participants',
  },
  {
    id: 8,
    eventStatus: 'completed',
    title: 'B3',
    tags: ['BOOTCAMP'],
    tagColors: ['blue'],
    image: kineticEngineImg,
    description: 'Web Development Bootcamp. A beginner-friendly bootcamp introducing students to Web Dev, Git & GitHub essentials and LinkedIn optimisation.',
    entryFee: 'Free',
    date: '11 Feb, 2023',
    venue: 'CPBYTE Campus',
    slotsLeft: '250 / 250',
    duration: '3 days',
    difficulty: 'Beginner',
    result: '250 Participants',
  },
]

export const ARCHIVES = [
  { id: 1, title: 'OFF-GRID 2.0', image: offgridImg, meta: '36H HACKATHON · KIET · 10–11 APR 2026', gradient: 'linear-gradient(135deg, #1a0000 0%, #3d0000 40%, #1a0a00 100%)' },
  { id: 2, title: 'DEV 102', meta: 'BACKEND BOOTCAMP · APR 2025', gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a3e 50%, #0a0a1a 100%)' },
  { id: 3, title: 'DEV 101', meta: 'WEB & ANDROID · 4 OCT, 2024', gradient: 'linear-gradient(135deg, #001a1a 0%, #004444 50%, #001a33 100%)' },
]
